# Generated by Django 4.2 on 2024-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zip_code", models.CharField(max_length=5)),
                ("passcode", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="household",
            constraint=models.UniqueConstraint(
                fields=("street_address", "city", "state", "zip_code"),
                name="unique_household_address",
            ),
        ),
    ]
