# Generated by Django 4.2 on 2024-10-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_household_created_at_alter_household_passcode_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={},
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("household_id", "name"),
                name="unique_member_name_within_household",
            ),
        ),
    ]
