# Generated by Django 4.2 on 2024-10-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_alter_member_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
