# Generated by Django 4.2 on 2024-10-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_alter_member_password"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="member",
            name="unique_member_name_within_household",
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("household", "name"), name="unique_member_name_within_household"
            ),
        ),
    ]
